# Generated by Django 2.2.4 on 2019-08-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Todo')),
                ('description', models.TextField(verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('has_deadline', models.BooleanField(default=False, verbose_name='Has Deadline')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
