# Generated by Django 2.2.4 on 2019-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Todo')),
                ('description', models.TextField(verbose_name='Description')),
                ('has_deadline', models.BooleanField(default=False, verbose_name='Has Deadline')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
    ]
